//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpenses.Web.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TravelExpenses.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        public static string EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationSubject", resourceCulture);
            }
        }
        
        public static string EmailConfirmationBody {
            get {
                return ResourceManager.GetString("EmailConfirmationBody", resourceCulture);
            }
        }
        
        public static string EmailConfirmationSent {
            get {
                return ResourceManager.GetString("EmailConfirmationSent", resourceCulture);
            }
        }
        
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        public static string RecoverPasswordSubject {
            get {
                return ResourceManager.GetString("RecoverPasswordSubject", resourceCulture);
            }
        }
        
        public static string RecoverPasswordBody {
            get {
                return ResourceManager.GetString("RecoverPasswordBody", resourceCulture);
            }
        }
        
        public static string RecoverPasswordEmailSent {
            get {
                return ResourceManager.GetString("RecoverPasswordEmailSent", resourceCulture);
            }
        }
        
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        public static string UserAlreadyBelogToGroup {
            get {
                return ResourceManager.GetString("UserAlreadyBelogToGroup", resourceCulture);
            }
        }
        
        public static string RequestJoinGroupSubject {
            get {
                return ResourceManager.GetString("RequestJoinGroupSubject", resourceCulture);
            }
        }
        
        public static string TheUser {
            get {
                return ResourceManager.GetString("TheUser", resourceCulture);
            }
        }
        
        public static string RequestJoinGroupBody {
            get {
                return ResourceManager.GetString("RequestJoinGroupBody", resourceCulture);
            }
        }
        
        public static string WishToAccept {
            get {
                return ResourceManager.GetString("WishToAccept", resourceCulture);
            }
        }
        
        public static string WishToReject {
            get {
                return ResourceManager.GetString("WishToReject", resourceCulture);
            }
        }
        
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        public static string RequestJoinGroupEmailSent {
            get {
                return ResourceManager.GetString("RequestJoinGroupEmailSent", resourceCulture);
            }
        }
    }
}
