//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpenses.Prism.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TravelExpenses.Prism.Resources.Resource.es", typeof(Resource_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        internal static string TaxiHistory {
            get {
                return ResourceManager.GetString("TaxiHistory", resourceCulture);
            }
        }
        
        internal static string AddTrip {
            get {
                return ResourceManager.GetString("AddTrip", resourceCulture);
            }
        }
        
        internal static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        internal static string PlaqueError1 {
            get {
                return ResourceManager.GetString("PlaqueError1", resourceCulture);
            }
        }
        
        internal static string PlaqueError2 {
            get {
                return ResourceManager.GetString("PlaqueError2", resourceCulture);
            }
        }
        
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        internal static string Plaque {
            get {
                return ResourceManager.GetString("Plaque", resourceCulture);
            }
        }
        
        internal static string PlaquePlaceHolder {
            get {
                return ResourceManager.GetString("PlaquePlaceHolder", resourceCulture);
            }
        }
        
        internal static string CheckPlaque {
            get {
                return ResourceManager.GetString("CheckPlaque", resourceCulture);
            }
        }
        
        internal static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        internal static string NumberOfTrips {
            get {
                return ResourceManager.GetString("NumberOfTrips", resourceCulture);
            }
        }
        
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string StartTrip {
            get {
                return ResourceManager.GetString("StartTrip", resourceCulture);
            }
        }
        
        internal static string NewTrip {
            get {
                return ResourceManager.GetString("NewTrip", resourceCulture);
            }
        }
        
        internal static string SeeTaxiHistory {
            get {
                return ResourceManager.GetString("SeeTaxiHistory", resourceCulture);
            }
        }
        
        internal static string AdminMyUserGroup {
            get {
                return ResourceManager.GetString("AdminMyUserGroup", resourceCulture);
            }
        }
        
        internal static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        internal static string ReportAnIncident {
            get {
                return ResourceManager.GetString("ReportAnIncident", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        internal static string DocumentPlaceHolder {
            get {
                return ResourceManager.GetString("DocumentPlaceHolder", resourceCulture);
            }
        }
        
        internal static string DocumentError {
            get {
                return ResourceManager.GetString("DocumentError", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        internal static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        internal static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        internal static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        internal static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        internal static string PasswordConfirmError1 {
            get {
                return ResourceManager.GetString("PasswordConfirmError1", resourceCulture);
            }
        }
        
        internal static string PasswordConfirmError2 {
            get {
                return ResourceManager.GetString("PasswordConfirmError2", resourceCulture);
            }
        }
        
        internal static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        internal static string RegisterAs {
            get {
                return ResourceManager.GetString("RegisterAs", resourceCulture);
            }
        }
        
        internal static string RegisterAsError {
            get {
                return ResourceManager.GetString("RegisterAsError", resourceCulture);
            }
        }
        
        internal static string RegisterAsPlaceHolder {
            get {
                return ResourceManager.GetString("RegisterAsPlaceHolder", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string PictureSource {
            get {
                return ResourceManager.GetString("PictureSource", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        internal static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        internal static string PasswordRecover {
            get {
                return ResourceManager.GetString("PasswordRecover", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string ResetLinkPassword {
            get {
                return ResourceManager.GetString("ResetLinkPassword", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPasswordError {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPasswordError2 {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError2", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        internal static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        internal static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        internal static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        internal static string EndTrip {
            get {
                return ResourceManager.GetString("EndTrip", resourceCulture);
            }
        }
        
        internal static string GeolocationError {
            get {
                return ResourceManager.GetString("GeolocationError", resourceCulture);
            }
        }
        
        internal static string ConfirmAddress {
            get {
                return ResourceManager.GetString("ConfirmAddress", resourceCulture);
            }
        }
    }
}
